import { useLanguage } from "../context/LanguageProvider";

export const getLabel = (id) => {
  const { language } = useLanguage(); // Ottieni la lingua dal contesto
  return labels[language][id] || labels.it[id]; // Restituisci l'etichetta in base alla lingua corrente, con un fallback all'italiano
};

export const labels = {
  it: {
    name: "Nome",
    surname: "Cognome",
    email: "Email",
    phone: "Telefono",
    route: "Tratta",
    dateStart: "Data Partenza",
    timeStart: "Orario Partenza",
    dateReturn: "Data Ritorno",
    timeReturn: "Orario Ritorno",
    notes: "Note",
    passengers: "Passeggeri",
    duration: "Durata",
    addReturn: "Aggiungi Ritorno",
    messagePlaceholder: "Inserisci qui eventuali richieste speciali",
    goToPayment: "vai al pagamento",
    back: "Indietro",
    backHome: "Torna alla Home",
    loading: "Caricamento...",
    selectRoute: "Seleziona una tratta",
    price: "Prezzo",
    message: "Messaggio",
    paymentCompleted: "Pagamento completato con successo!",
    thankYouBooking:
      "Grazie per la tua prenotazione. Riceverai una conferma via email.",
    paymentError: "Pagamento non riuscito",
    paymentErrorDescription:
      "Qualcosa è andato storto con il pagamento. Riprova più tardi o contatta l'assistenza.",
    send: "Invia",
    sending: "Invio...",
    insertMessage: "Inserisci qui il tuo messaggio",
    contacts: "Contatti",
    whatsapp: "WhatsApp",
    footerTitle: "Contattaci",
    footerBody: "Per maggiori informazioni, scrivici!",
    taxiInfoTitle: "Informazioni taxi",
    taxiInfoBody: "Servizio taxi disponibile su richiesta.",
    shipInfoTitle: "Informazioni nave",
    shipInfoBody: "Servizio navetta disponibile per il porto.",
    home: "Home",
    transfer: "Transfer",
    contactUs: "Contattaci",
    contactUsTitle: "Contattaci per maggiori informazioni",
    contactUsDescription:
      "Se hai domande o richieste, siamo a tua disposizione.",
    transferTitle: "Servizi di Transfer",
    transferBody: "Scopri i nostri servizi di transfer personalizzati.",
    favignanaTitle: "Favignana",
    favignanaBody: "Esplora le bellezze di Favignana.",
    paymentTitle: "Dettagli pagamento",
    paymentBody: "Verifica i dettagli e completa il pagamento.",
    CTAAbstract: "Inizia il tuo viaggio",
    CTATitle: "Prenota ora",
    CTABody: "Scegli la tua destinazione e prenota il tuo transfer.",
    CTAButton: "Prenota",
    descTitle: "Descrizione",
    descBody: "Scopri tutte le informazioni.",
    homeMasterTitle: "Benvenuto su Favignana Transfer",
    transferMasterTitle: "Prenota il tuo transfer",
    contactMasterTitle: "Contattaci per info",
    transferDescription:
      "Offriamo servizi di transfer personalizzati per Favignana e oltre.",
  },
  en: {
    name: "Name",
    surname: "Surname",
    email: "Email",
    phone: "Phone",
    route: "Route",
    dateStart: "Departure Date",
    timeStart: "Departure Time",
    dateReturn: "Return Date",
    timeReturn: "Return Time",
    notes: "Notes",
    passengers: "Passengers",
    duration: "Duration",
    addReturn: "Add Return",
    messagePlaceholder: "Enter any special requests here",
    goToPayment: "Go to Payment",
    back: "Back",
    backHome: "Back to Home",
    loading: "Loading...",
    selectRoute: "Select a route",
    price: "Price",
    message: "Message",
    paymentCompleted: "Payment completed successfully!",
    thankYouBooking:
      "Thank you for your booking. You will receive a confirmation via email.",
    paymentError: "Payment failed",
    paymentErrorDescription:
      "Something went wrong with the payment. Please try again later or contact support.",
    send: "Send",
    sending: "Sending...",
    insertMessage: "Enter your message here",
    contacts: "Contacts",
    whatsapp: "WhatsApp",
    footerTitle: "Contact Us",
    footerBody: "For more information, write to us!",
    taxiInfoTitle: "Taxi Information",
    taxiInfoBody: "Taxi service available upon request.",
    shipInfoTitle: "Ship Information",
    shipInfoBody: "Shuttle service available to the port.",
    home: "Home",
    transfer: "Transfer",
    contactUs: "Contact Us",
    contactUsTitle: "Contact Us for More Information",
    contactUsDescription:
      "If you have any questions or requests, we are at your service.",
    transferTitle: "Transfer Services",
    transferBody: "Discover our personalized transfer services.",
    favignanaTitle: "Favignana",
    favignanaBody: "Explore the beauty of Favignana.",
    paymentTitle: "Payment Details",
    paymentBody: "Check the details and complete the payment.",
    CTAAbstract: "Start Your Journey",
    CTATitle: "Book Now",
    CTABody: "Choose your destination and book your transfer.",
    CTAButton: "Book",
    descTitle: "Description",
    descBody: "Discover all the information.",
    homeMasterTitle: "Welcome to Favignana Transfer",
    transferMasterTitle: "Book Your Transfer",
    contactMasterTitle: "Contact Us for Info",
    transferDescription:
      "We offer personalized transfer services to Favignana and beyond.",
  },
};
